### ISSUE TITLE
[Question] Better control over warnings.

### ISSUE THREAD

**Issue by lang-m** [PyCQA/flake8-docstrings#10]
The link to the bug tracker in the README is broken so I am asking here.

`pydocstyle` allows more control than this package with the additional options `match` and `match-dir`. Furthermore, these seem to have different defaults when using `pydocstyle` as stand-alone vs as part of `flake8` (most notably `pydocstyle` by default ignores test files (`test_*.py`)).

Most of this behaviour could be mimicked in `flake8-docstrings` by using `flake8`s `per-file-ignores`. This doesn't seem to have any effect? Are there any other ways to ignore specific warnings in certain files (matched with some (regular) expression)?

**Comment by asottile** [comment]
I can't help unless you show what you've tried and what isn't working

**Comment by lang-m** [comment]
The issue has been solved, everything is working correctly. (I've had conflicting configuration for `flake8` in different files, namely `setup.cfg` and `.flake8`)
