### ISSUE TITLE
noqa comment placement inconsistent with pydocstyle for multi-line function parameters

### ISSUE THREAD

**Issue by kevinoid** [PyCQA/flake8-docstrings#24]
If a function is defined with the parameters spanning multiple lines, `# noqa` must be placed differently for flake8-docstrings than pydocstyle.  For example:

```python
def myfunc(
    one_or_more_parameters_with_long_names_causing_wrapping
):
    pass
```

With flake8 4.0.1 and flake8-docstrings 1.6.0, if `# noqa: D103` is placed on line 1 after `myfunc(`, D103 does not appear in flake8 output, but does appear in pydocstyle output.  If `# noqa: D103` is placed on line 3 after `):`, D103 appears in flake8 output, but does not appear in pydocstyle output.

I'm not sure whether the bug/incompatibility is in this package or flake8 or pydocstyle.  I'd appreciate your thoughts.

Thanks,
Kevin

**Comment by asottile** [comment]
yeah pydocstyle has their own ideas about `noqa` that are incompatible with flake8

flake8 you must place the noqa on the line which causes the error rather than willy nilly near the error
