### ISSUE TITLE
New release needed to fix obsolete homepage in previous one

### ISSUE THREAD

**Issue by ssbarnea** [PyCQA/flake8-docstrings#30]
While the correct project homepage was corrected inside `setup.cfg`, that is not visible on pypi, as we need to make a new release.

**Comment by asottile** [comment]
it's not a huge deal -- it'll get fixed when we release

**Comment by asottile** [comment]
there's a nice text on the current landing page:

> This has migrated to GitHub.com/pycqa/flake8-docstrings
