### ISSUE TITLE
D100, D103 false positives for private modules not re-exported using '__all__'

### ISSUE THREAD

**Issue by danieleades** [PyCQA/flake8-docstrings#32]
when `__all__` is set for a module, any submodules not included in the `__all__` statement should probably be considered private modules. As such, these private modules shouldn't trigger the lints requiring public items to be documented.

**Comment by danieleades** [comment]
interestingly, when I configure vscode to use flake8 it seems to handle this correctly- i only see these errors for modules included in `__all__`. When i run flake8 using pre-commit, i see the false positives. Is this related to the way files are passed to flake8?

**Comment by asottile** [comment]
flake8-docstrings doesn't implement any checks
