### ISSUE TITLE
Add support for spell chcker

### ISSUE THREAD

**Issue by heitorPB** [PyCQA/flake8-docstrings#6]
It would be great to have some support for running a spell checker on the docstrings.

**Comment by asottile** [comment]
this tool is a simple wrapper around pydocstyle and does not implement any features

**Comment by heitorPB** [comment]
So, where do you think it would be the best place to have a spell checker for the docstrings?

**Comment by asottile** [comment]
there are many spell checkers which already exist

**Comment by Akuli** [comment]
You might like `codespell`. You can just run `codespell foo.py`. It will check everything, including variable names etc, with reasonably few false positives.
