### ISSUE TITLE
Doesn't ignore tests by default

### ISSUE THREAD

**Issue by itaranto** [PyCQA/flake8-docstrings#65]
Stand-alone `pydocstyle` has `--match='(?!test_).*\.py'` by default, but it doesn't seem to be the case for `flake8-docstrings`.

**Comment by asottile** [comment]
you can use `per-file-ignores` to do the same

**Comment by itaranto** [comment]
> you can use `per-file-ignores` to do the same

But shouldn't be the default behavior?
Shouldn't this plugin be aligned with `pydocstyle`?

**Comment by asottile** [comment]
no it should not.  it is a flake8 plugin so you should expect it to work like flake8
