### ISSUE TITLE
How do I ignore warnings when at the top of a module file?

### ISSUE THREAD

**Issue by red8888** [PyCQA/flake8-docstrings#72]
I use sphinx and at the top of my py files I have this:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
my-module
=========
Some notes about my module
"""

```
These warning are incorrect in the this context:
```
1 blank line required between summary line and descriptionFlake8(D205)
First line should end with a periodFlake8(D400)
```

I can't put a blank line above `=======` because that breaks the headings and I also don't want to put a period after my heading. How can I ignore in just these cases?

**Comment by asottile** [comment]
there's no such option

**Comment by red8888** [comment]
@asottile I know this is out of scope, but figured I'd ask, do you know if this is also the case with ruff? Plan on switching over at some point.

**Comment by asottile** [comment]
it's probably the same given ruff tends to just rip off the python implementations and contribute nothing back

**Comment by sigmavirus24** [comment]
Also pydocstyle is dead and deprecated, so this isn't even the best place to ask this question but you won't get help from the maintainer there
